plugins {
    id 'java'
}

group = 'ru.basted'
version = '0.1'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform("org.junit:junit-bom:${junitVersion}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation "org.seleniumhq.selenium:selenium-java:${seleniumVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"

    testImplementation "org.slf4j:slf4j-api:${slf4jVersion}"
    testImplementation "org.apache.logging.log4j:log4j-slf4j2-impl:${log4jVersion}"
    testImplementation "org.apache.logging.log4j:log4j-core:${log4jVersion}"

    testImplementation "org.aeonbits.owner:owner:${ownerVersion}"
}

test {
    useJUnitPlatform()
    systemProperties = System.getProperties() as Map<String, ? extends Object>
}